baseURL = 'https://gal.saop.cc/'
languageCode = 'zh-CN'
title = 'GGS'

[[menus.main]]
name = 'GGS'
url = 'https://gal.saop.cc/'
weight = 5

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = true
    min = "0.145.0"
