name: Build and Deploy with Hexo
env:
  GAL_SITE_TOKEN: ${{ secrets.GAL_SITE_TOKEN }}
  BAIDU_TOKEN: ${{ secrets.BAIDU_TOKEN }}
  BING_TOKEN: ${{ secrets.BING_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Use Node.js 24.4.1
        uses: actions/setup-node@v4
        with:
          node-version: "24.4.1"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install
          npm install hexo@latest --save
          npm install hexo-deployer-git@latest --save
          npm install highlight.js@latest --save
      - name: Install Hexo CLI
        run: npm install -g hexo-cli@latest
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Run Hexo Commands
        run: |
          hexo cl
          hexo g
          hexo swpp
          hexo d
